name: Docker Image CI

on:
  push:
    branches: [ "main","develop" ]
  pull_request:
    branches: [ "main","develop" ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin
      
    - name: Set branch name
      id: branch
      run: echo "::set-output name=name::$(echo $GITHUB_REF | sed 's/refs\/heads\///')"
          
    - name: Build the Docker image
      run: |
        IMAGE_TAG=$(echo "${{ steps.branch.outputs.name }}-$(date +'%Y%m%d%H%M%S')")
        docker build -f prod.Dockerfile -t $IMAGE_TAG .
        echo "::set-output name=image_tag::$IMAGE_TAG"
        
    - name: Push Docker image to Docker registry
      run: |
        IMAGE_TAG="${{ steps.build.outputs.image_tag }}"
        docker tag $IMAGE_TAG ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_TAG
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/$IMAGE_TAG
        
    #- name: Merge into develop
    #  if: github.ref == 'refs/heads/main'
    #  uses: pullreminders/merge-methods@v2
    #  with:
    #    github-token: ${{ secrets.GITHUB_TOKEN }}
    #    method: merge
    #    branch: develop
    
